import { SectionBatchRenderer } from '@dds/renderer';

const article = {
  id: 'home',
  type: 'section',
  subject: {
    title: 'Age of Abundance',
    subtitle: 'A post-scarcity civilization operating manual',
    summary:
      'An open, living wiki about the transition from scarcity economics to abundance systems — the tools, frameworks, and patterns that let communities coordinate at planetary scale.',
    category: 'Overview',
  },
  content: {
    body: 'Abundance is not a gift from the future — it is a design problem in the present. This wiki is a working notebook: incomplete, opinionated, and always being revised.',
    paragraphs: [
      {
        subtitle: 'What this wiki is',
        description:
          'A structured archive of ideas, primitives, and case studies for building post-scarcity infrastructure. Every page is parametric — the same UniversalSection schema powers the home page, article bodies, tables of contents, and cross-link indexes.',
      },
      {
        subtitle: 'How it is built',
        description:
          'Every surface is a plugin renderer registered against @dds/renderer. The wiki article body you are reading is generated by the wiki-article plugin, which ships with semantic landmarks, slugged heading anchors, and ≤75ch editorial typography out of the box.',
        citations: [
          {
            text: 'UniversalSection schema',
            url: 'https://github.com/michaeldouglas319/dds-platform',
          },
        ],
      },
      {
        subtitle: 'Editorial principles',
        description:
          'Accessibility-first, long-form readable, mobile responsive, and always backward compatible. If a change would break an existing article, it is a new plugin — not a core fork.',
      },
    ],
    items: [
      'Economic primitives',
      'Coordination protocols',
      'Governance patterns',
      'Case studies',
    ],
  },
  display: { layout: 'wiki-article' },
  meta: { seeAlsoLabel: 'Further reading' },
};

export default function Home() {
  return (
    <main data-page="wiki-home">
      <a href="#wiki-article-home" className="wiki-skip-link">
        Skip to article
      </a>
      <SectionBatchRenderer sections={[article]} />
    </main>
  );
}
