/**
 * Wiki-link parser and slug resolver.
 *
 * Wiki-links are written inline in article body paragraphs as:
 *
 *   [[Slug or Title]]
 *   [[Slug or Title|Display text]]
 *
 * The parser tokenizes a paragraph into a mixed list of text spans and
 * link descriptors. Links are resolved against the article index so a
 * broken link can be rendered with an explicit `data-broken="true"` state.
 *
 * We deliberately avoid `remark` and other heavy toolchains for this first
 * pass: the grammar is tiny, the transform is pure, and the output lives on
 * the server where it is static-generated by Next's App Router. If we later
 * swap to MDX the article paragraphs stay shape-compatible.
 */

import { slugByTitle, articles, canonicalizeSlug } from '../data/articles.js';

/**
 * @typedef {{ kind: 'text', value: string }} WikiTextToken
 * @typedef {{
 *   kind: 'link',
 *   target: string,   // The raw target written inside the brackets, trimmed.
 *   slug: string|null,// Resolved canonical slug, or null when the link is broken.
 *   display: string,  // What should be shown to the reader.
 *   broken: boolean
 * }} WikiLinkToken
 * @typedef {WikiTextToken | WikiLinkToken} WikiToken
 */

// [[target]] or [[target|display]]; target and display are non-empty and must
// not contain `[`, `]` or `|` (for target). Display may contain spaces.
const WIKI_LINK_RE = /\[\[([^\[\]|]+?)(?:\|([^\[\]]+?))?\]\]/g;

/**
 * Resolve a raw wiki-link target to a canonical slug, or null if unknown.
 * Matching is case-insensitive against both the article slug and the
 * article title.
 *
 * @param {string} target
 * @returns {string|null}
 */
export function resolveSlug(target) {
  if (!target) return null;
  const normalized = canonicalizeSlug(target);
  if (!normalized) return null;
  return slugByTitle[normalized] ?? null;
}

/**
 * Tokenize an article paragraph into text spans and wiki-link descriptors.
 * Preserves the original order so the renderer can stream them out in-place.
 *
 * @param {string} source
 * @returns {WikiToken[]}
 */
export function parseWikiLinks(source) {
  if (!source) return [];
  /** @type {WikiToken[]} */
  const tokens = [];
  let cursor = 0;
  // Reset the regex since it is a module-scoped /g literal.
  WIKI_LINK_RE.lastIndex = 0;
  let match;
  while ((match = WIKI_LINK_RE.exec(source)) !== null) {
    const [full, rawTarget, rawDisplay] = match;
    const start = match.index;
    if (start > cursor) {
      tokens.push({ kind: 'text', value: source.slice(cursor, start) });
    }
    const target = rawTarget.trim();
    const slug = resolveSlug(target);
    const display = (rawDisplay ?? target).trim();
    tokens.push({
      kind: 'link',
      target,
      slug,
      display,
      broken: slug === null,
    });
    cursor = start + full.length;
  }
  if (cursor < source.length) {
    tokens.push({ kind: 'text', value: source.slice(cursor) });
  }
  return tokens;
}

/**
 * Return every outbound wiki-link from an article's body, de-duplicated
 * on the resolved slug. Broken links are excluded from the outbound index
 * but are still visible to the renderer via `parseWikiLinks`.
 *
 * @param {import('../data/articles.js').WikiArticle} article
 * @returns {string[]} slugs referenced by this article
 */
export function outboundLinks(article) {
  /** @type {Set<string>} */
  const seen = new Set();
  for (const paragraph of article.content.paragraphs) {
    for (const token of parseWikiLinks(paragraph.description)) {
      if (token.kind === 'link' && token.slug) {
        seen.add(token.slug);
      }
    }
  }
  return [...seen];
}

/**
 * Compute the backlink index — for each article, the list of *other* articles
 * whose body links to it. The result is memoized on module evaluation so
 * the dynamic `/wiki/[slug]` route never recomputes it on demand.
 *
 * @returns {Record<string, { slug: string; title: string }[]>}
 */
export function computeBacklinkIndex() {
  /** @type {Record<string, { slug: string; title: string }[]>} */
  const index = {};
  for (const article of articles) {
    const outbound = outboundLinks(article);
    for (const targetSlug of outbound) {
      if (targetSlug === article.slug) continue; // self-links never count
      if (!index[targetSlug]) index[targetSlug] = [];
      index[targetSlug].push({
        slug: article.slug,
        title: article.subject.title,
      });
    }
  }
  // Sort each bucket alphabetically so the render order is stable.
  for (const key of Object.keys(index)) {
    index[key].sort((a, b) => a.title.localeCompare(b.title));
  }
  return index;
}

export const backlinkIndex = computeBacklinkIndex();
