/**
 * DEPRECATED - Routes Configuration
 *
 * ⚠️  THIS FILE IS DEPRECATED AND NO LONGER MAINTAINED
 *
 * USE INSTEAD: lib/config/routes.generated.ts
 *
 * SINGLE SOURCE OF TRUTH: /public/registry/routes.json
 *
 * This file is kept for backward compatibility only.
 * All routes are now auto-generated from the routes registry.
 *
 * MIGRATION GUIDE:
 * If you're importing from this file, update your imports:
 *
 * OLD (Deprecated):
 *   import { getDashboardRoutes } from '@/lib/config/routes.config'
 *
 * NEW (Recommended):
 *   import { getDashboardRoutes } from '@/lib/config/routes.generated'
 *
 * All functions are identical - only the import location changed.
 *
 * WHY THIS CHANGED:
 * - Eliminates duplication (routes declared only in registry)
 * - Auto-discovered from /app directory structure
 * - Always in sync - no manual updates needed
 * - Single source of truth approach
 *
 * The registry is auto-generated by:
 *   npm run generate-routes-registry    (manual)
 *   npm run build                       (auto-runs generator)
 */

/**
 * Re-exports from routes.generated for backward compatibility
 * These will be removed in a future version.
 */

export {
  getAllRoutes,
  getRouteByPath,
  getRouteById,
  getRoutesByAccessLevel,
  getPublicRoutes,
  getMemberPlusRoutes,
  getPartnerRoutes,
  getAdminRoutes,
  getDashboardRoutes,
  getNavigationRoutes,
  routeRequiresAuth,
  getRegistryMetadata,
  getFullRegistry,
  type RouteMetadata,
  type RoutesRegistry,
} from './routes.generated'
