/**
 * Sample wiki article rendered on the home page. Hand-authored as a
 * UniversalSection to demonstrate the schema-driven editorial pipeline.
 *
 * Subsequent sessions will replace this with MDX/frontmatter sourcing,
 * filesystem-driven topic loading, and remote CMS integration. The renderer
 * stays the same — only the source of UniversalSection objects changes.
 */
import type { UniversalSection } from '@dds/types';

export const homeArticle: UniversalSection = {
  id: 'home',
  type: 'entry',
  name: 'Welcome',
  page: '/',
  display: {
    layout: 'wiki-article',
    headingLevel: 1,
  },
  subject: {
    category: 'The Age of Abundance',
    title: 'A wiki for the abundance era',
    subtitle:
      'Open, schema-driven knowledge for the technologies, communities, and ideas shaping a post-scarcity world.',
    tags: {
      type: 'overview',
      status: 'living document',
    },
  },
  content: {
    body:
      'This wiki is the canonical reference for The Age of Abundance — a record of the people, projects, and primitives that move us from scarcity to plenty. Every page is written as a UniversalSection, rendered by the @dds/renderer plugin system, and themed through CSS custom properties so it stays accessible and editable forever.',
    paragraphs: [
      {
        subtitle: 'How this wiki is built',
        description:
          'Articles are not HTML files — they are typed UniversalSection records. A small registry of renderer plugins translates those records into accessible long-form pages, sidebars, infoboxes, and tables of contents. The same schema can be authored by humans, generated by agents, or synced from any structured source.',
      },
      {
        subtitle: 'What lives here',
        description:
          'Topics on energy, computation, biology, governance, art, and the connective tissue between them. Each topic is a small, well-cited entry that links generously to its neighbors. Backlinks, revisions, and full-text search will make the graph navigable as the corpus grows.',
      },
      {
        subtitle: 'How to contribute',
        description:
          'Open a pull request that adds a UniversalSection JSON file to data/. Every section gets a renderer, every renderer is a plugin, and every plugin is hot-swappable. No content lives outside the schema; no styling lives outside the theme tokens.',
      },
    ],
    highlights: [
      {
        subtitle: 'Schema',
        description: 'UniversalSection (typed, additive)',
      },
      {
        subtitle: 'Renderer',
        description: '@dds/renderer plugin registry',
      },
      {
        subtitle: 'Accessibility',
        description: 'WCAG AA minimum, AAA on body text',
      },
      {
        subtitle: 'Themes',
        description: '9 variants via data-theme-variant',
      },
    ],
    items: [
      'Energy: fusion, geothermal, transmission',
      'Computation: compilers, agents, formal methods',
      'Biology: longevity, synthetic, climate',
      'Governance: protocols, prediction markets, public goods',
      'Art: editorial, generative, immersive',
    ],
  },
};
