/**
 * AUTO-GENERATED FILE
 *
 * This file is generated automatically by scripts/generate-static-objects.ts
 * when you run: npm run generate-static-objects
 *
 * To update: Add/remove models from /public/assets/models/, then run the script again.
 * Do NOT edit this file directly.
 */

import * as THREE from 'three';
import type { V3StaticObject } from './v3.config';

/**
 * Automatically discovered static objects from /public/assets/models/
 *
 * Generated models are positioned in a grid layout.
 * Adjust positions, rotations, and scales in v3.config.ts staticObjects array.
 */
export const GENERATED_STATIC_OBJECTS: V3StaticObject[] = [
    {
      id: 'model-assembly_line_gltf',
      modelPath: '/assets/models/assembly_line_gltf/scene.gltf',
      position: new THREE.Vector3(-10, 0, -10),
      scale: 0.1,
      rotation: { x: 0, y: 0, z: 0 },
    },

    // {
    //   id: 'model-black_honey_robotic_arm_gltf',
    //   modelPath: '/assets/models/black_honey_robotic_arm_gltf/scene.gltf',
    //   position: new THREE.Vector3(-50, 0, -10),
    //   scale: 0.1,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },

    // {
    //   id: 'model-city',
    //   modelPath: '/assets/models/city/scene.gltf',
    //   position: new THREE.Vector3(0, -20, 0),
    //   scale: 2,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },
    // {
    //   id: 'model-sci-fi_solar_power_tower_free-download',
    //   modelPath: '/assets/models/sci-fi_solar_power_tower_free-download.glb',
    //   position: new THREE.Vector3(0, -20, 0),
    //   scale: .02,
    //   rotation: { x: -61, y: 0, z: 61 },
    // },
    // {
    //   id: 'model-dron_low_poly_3d_model_gltf',
    //   modelPath: '/assets/models/dron_low_poly_3d_model_gltf/scene.gltf',
    //   position: new THREE.Vector3(5, 0, -10),
    //   scale: 0.01,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },

    {
      id: 'model-drone_uav_wing_desert_camo_gltf',
      modelPath: '/assets/models/drone_uav_wing_desert_camo_gltf/scene.gltf',
      position: new THREE.Vector3(-10, 0, 0),
      scale: 1,
      rotation: { x: 0, y: 0, z: 0 },
    },

    // {
    //   id: 'model-future-island',
    //   modelPath: '/assets/models/future-island/scene.gltf',
    //   position: new THREE.Vector3(-10, 0, -10),
    //   scale: .5,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },

    {
      id: 'model-aircraft_presentation_cover_draco',
      modelPath: '/assets/models/aircraft_presentation_cover_draco.glb',
      position: new THREE.Vector3(0, 0, -50),
      scale: 4,
      rotation: { x: 0, y: 0, z: 0 },
    },

    // {
    //   id: 'model-gourmet_factory',
    //   modelPath: '/assets/models/gourmet_factory/scene.gltf',
    //   position: new THREE.Vector3(50, 0, -50),
    //   scale: 0.01,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },

    // {
    //   id: 'model-lowpoly_city',
    //   modelPath: '/assets/models/lowpoly_city/scene.gltf',
    //   position: new THREE.Vector3(-100, 0, 0),
    //   scale: 0.01,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },
    // Cad model 
    // {
    //   id: 'model-ventis_3015_aj',
    //   modelPath: '/assets/models/ventis_3015_aj/scene.gltf',
    //   position: new THREE.Vector3(-50, 0, 0),
    //   scale: 0.01,
    //   rotation: { x: 0, y: 0, z: 0 },
    // },
];
